services:
  - type: web
    name: mamoanalyzer
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PORT
        value: 5000
