name: Build and deploy Python API to Azure Web App
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      
      - name: Archive backend contents + requirements
     run: |
       mkdir tmp-backend
       cp -R backend/* tmp-backend/
       cp requirements.txt tmp-backend/
       cd tmp-backend
       zip -r ../backend.zip .
       cd ..
       rm -rf tmp-backend
          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-package

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "mamoanalyzer-backend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend.zip
